---
abstract: 'Perl implementation of the Telegram Bot API'
author:
  - 'Roberto Frenna <robertof@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Telegram-BotAPI
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  JSON::MaybeXS: '0'
  LWP::Protocol::https: '0'
  LWP::UserAgent: '0'
resources:
  bugtracker: https://github.com/Robertof/perl-www-telegram-botapi/issues
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/Robertof/perl-www-telegram-botapi
version: '0.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
